#!/usr/bin/env node
// Drift check against the live Convertlyft server (D3).
//   node scripts/check-drift.mjs          fail if a skill names a tool, REST path or scope that is not live,
//                                         or if the generated API reference is stale
//   node scripts/check-drift.mjs --write  regenerate skills/getting-started-with-convertlyft/references/convertlyft-api.md
// Sources: MCP tools/list (?features=all, no token), /.well-known/convertlyft-capabilities.json, /openapi.json.
import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { toolsTable } from './lint-skills-lib.mjs';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const SKILLS = join(ROOT, 'skills');
const EVALS = join(ROOT, 'evals');
const GENERATED = join(SKILLS, 'getting-started-with-convertlyft', 'references', 'convertlyft-api.md');
const SITE = 'https://convertlyft.com';
const MCP = 'https://mcp.convertlyft.com/mcp?features=all';
const MANIFEST = `${SITE}/.well-known/convertlyft-capabilities.json`;
const OPENAPI = `${SITE}/openapi.json`;
const TOOL_RE = /(?<![A-Za-z0-9])cvl_(?!pat_)[a-z][a-z0-9_]*[a-z0-9]/g;
const PATH_RE = /\b(GET|POST)\s+https:\/\/convertlyft\.com(\/api\/[^\s`)?|]+)/g;

async function getJson(url, init) {
  const res = await fetch(url, init);
  if (!res.ok) throw new Error(`${url} answered ${res.status}`);
  return res.json();
}

async function liveTools() {
  const body = await getJson(MCP, {
    method: 'POST',
    headers: { 'content-type': 'application/json', accept: 'application/json, text/event-stream' },
    body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list' }),
  });
  return body.result.tools;
}

// Every REST route the live server documents, as "METHOD /path" with [name]/[id] placeholders kept.
function liveRoutes(manifest, openapi) {
  const routes = [];
  for (const [path, ops] of Object.entries(openapi.paths)) for (const m of Object.keys(ops)) routes.push(`${m.toUpperCase()} ${path}`);
  for (const e of [...manifest.endpoints, ...manifest.writes.endpoints]) routes.push(`${e.method} ${e.path}`);
  return routes;
}
const routeMatches = (route, method, path) => {
  const [m, p] = route.split(' ');
  if (m !== method) return false;
  const re = new RegExp('^' + p.replace(/[.*+?^${}()|\\]/g, '\\$&').replace(/\\\[[a-z_]+\\\]|\[[a-z_]+\]/g, '[^/]+') + '$');
  return re.test(path);
};

// The canonical REST twin for a tool: its own OpenAPI operation, else a manifest write endpoint
// whose description names the tool, else none.
function twinOf(tool, manifest, openapi) {
  const op = openapi.paths[`/api/tools/${tool}`];
  if (op) return `${Object.keys(op)[0].toUpperCase()} /api/tools/${tool}`;
  const named = {
    cvl_remember: 'POST /api/memory',
    cvl_operator_run: 'POST /api/operator/run',
    cvl_crawl_start: 'POST /api/crawl',
  };
  const t = named[tool];
  if (t && manifest.writes.endpoints.some((e) => `${e.method} ${e.path}` === t)) return t;
  return null;
}

function generateReference(tools, manifest, openapi) {
  const scopes = Object.fromEntries(manifest.mcp.tools.map((t) => [t.name, t.scopes]));
  const out = [
    '# Convertlyft API reference',
    '',
    'Generated by `node scripts/check-drift.mjs --write` from the live server:',
    `MCP \`tools/list\` at \`${MCP}\`, \`${MANIFEST}\` and \`${OPENAPI}\`.`,
    'Do not edit by hand; CI fails when this file and the live server disagree.',
    '',
    `MCP endpoint: \`${manifest.mcp.endpoint}\` (protocol ${manifest.mcp.spec_revision}).`,
    `REST: \`${SITE}\`, header \`Authorization: Bearer ${manifest.auth.token_prefix}…\`. GET arguments go in the query string, POST arguments in a JSON body.`,
    `Timestamps: ${manifest.timestamps.format}.`,
    '',
    '| MCP tool | Title | Reads or writes | REST twin | Scopes |',
    '|---|---|---|---|---|',
  ];
  for (const t of tools) {
    const twin = twinOf(t.name, manifest, openapi);
    const rw = t.annotations?.readOnlyHint ? 'reads' : 'writes';
    const sc = scopes[t.name];
    const scopeCell = sc === undefined ? 'not in manifest' : sc.length ? sc.map((s) => `\`${s}\``).join(', ') : 'none';
    out.push(`| \`${t.name}\` | ${(t.title || '').replace(/\|/g, '\\|')} | ${rw} | ${twin ? `\`${twin.replace(' ', ' ' + SITE)}\`` : 'none (MCP only)'} | ${scopeCell} |`);
  }
  return out.join('\n') + '\n';
}

function walk(dir, files = []) {
  if (!existsSync(dir)) return files;
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (e === 'results') continue;
    if (statSync(p).isDirectory()) walk(p, files);
    else if (/\.(md|ya?ml)$/.test(e)) files.push(p);
  }
  return files;
}

const [tools, manifest, openapi] = await Promise.all([liveTools(), getJson(MANIFEST), getJson(OPENAPI)]);
const reference = generateReference(tools, manifest, openapi);
if (process.argv.includes('--write')) {
  writeFileSync(GENERATED, reference);
  console.log(`wrote ${GENERATED} (${tools.length} tools)`);
  process.exit(0);
}

const live = new Set(tools.map((t) => t.name));
const routes = liveRoutes(manifest, openapi);
const manifestScopes = new Set([...manifest.scopes, ...manifest.writes.scopes]);
const toolScopes = Object.fromEntries(manifest.mcp.tools.map((t) => [t.name, t.scopes]));
const problems = [];
const rel = (p) => p.slice(ROOT.length).replace(/\\/g, '/').replace(/^\//, '');

for (const file of [...walk(SKILLS), ...walk(EVALS)]) {
  if (file === GENERATED) continue;
  const text = readFileSync(file, 'utf8');
  for (const t of new Set(text.match(TOOL_RE) || [])) if (!live.has(t)) problems.push(`${rel(file)}: names ${t}, which is not a live tool`);
  for (const m of text.matchAll(PATH_RE)) {
    if (!routes.some((r) => routeMatches(r, m[1], m[2]))) problems.push(`${rel(file)}: ${m[1]} ${m[2]} is not a live REST route`);
  }
  for (const m of text.matchAll(/`([a-z]+:(read|write|run))`/g)) {
    if (!manifestScopes.has(m[1])) problems.push(`${rel(file)}: scope ${m[1]} is not in the live manifest`);
  }
  if (file.endsWith('SKILL.md')) {
    for (const [tool, row] of toolsTable(text)) {
      if (!live.has(tool)) continue;
      const twin = twinOf(tool, manifest, openapi);
      const named = row.twin.match(/^`(GET|POST) https:\/\/convertlyft\.com(\S+)`$/);
      if (twin && !named) problems.push(`${rel(file)}: ${tool} has a REST twin (${twin}) but the table says "${row.twin}"`);
      else if (!twin && named) problems.push(`${rel(file)}: ${tool} has no REST twin but the table names ${named[1]} ${named[2]}`);
      else if (twin && named && `${named[1]} ${named[2]}` !== twin) problems.push(`${rel(file)}: ${tool} REST twin is ${twin}, table says ${named[1]} ${named[2]}`);
      const want = toolScopes[tool];
      if (want) {
        const got = [...row.scope.matchAll(/`([a-z]+:[a-z]+)`/g)].map((x) => x[1]).sort();
        if (got.join(',') !== [...want].sort().join(',')) problems.push(`${rel(file)}: ${tool} scopes are ${want.join(', ') || 'none'}, table says ${row.scope}`);
      }
    }
  }
}

const current = existsSync(GENERATED) ? readFileSync(GENERATED, 'utf8').replace(/\r\n/g, '\n') : '';
if (current !== reference) problems.push(`${rel(GENERATED)} is stale: run node scripts/check-drift.mjs --write`);

if (problems.length) {
  console.error(problems.join('\n'));
  console.error(`\n${problems.length} drift problem(s) against the live server.`);
  process.exit(1);
}
console.log(`drift ok: ${live.size} live tools, ${routes.length} REST routes, skills and evals match`);
